name: NickRequest
main: me.michaelkrauty.NickRequest.NickRequest
author: michaelkrauty
version: 1.0
commands:
   nickrequest:
     description: Request a nickname
     usage: /NickRequest <nickname>
   nickcheck:
     description: Check nickname requests
     usage: /NickCheck